version: "3"
services:
  # reverse proxy
  nginx:
    restart: always
    build: nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/ytdlr.skywarriors.net/fullchain.pem:/etc/letsencrypt/live/ytdlr.skywarriors.net/fullchain.pem
      - /etc/letsencrypt/live/ytdlr.skywarriors.net/privkey.pem:/etc/letsencrypt/live/ytdlr.skywarriors.net/privkey.pem

  # youtube download microservice
  downloader:
    restart: always
    build: downloader/
    volumes:
      - static:/static
    depends_on:
      - "webserver"

  # webserver API
  webserver:
    restart: always
    build: webserver/
    volumes:
      - static:/static
    depends_on:
      - "nginx"

  # discord bot
  bot:
    restart: always
    build: bot/
    depends_on:
      - "downloader"

volumes:
  static:
